### ISSUE TITLE
Bright Retrieval results bug

### ISSUE THREAD

**Issue by asparius** [embeddings-benchmark/results#20]
This [commit](https://github.com/embeddings-benchmark/results/commit/9355679ba99f43247e7ab393de04b603aa80b2eb) breaks load_results because BrightRetrieval results have missing evaluation_time. @Muennighoff

**Comment by Muennighoff** [comment]
Thanks for this! I've fixed it in https://github.com/embeddings-benchmark/results/commit/ef44d4f162c24a747cf8adb00ef4dc26235a5c8c 🙌
