### ISSUE TITLE
Renaming model_metaInstruct.json to model_meta.json

### ISSUE THREAD

**Issue by asparius** [embeddings-benchmark/results#22]
Task loading [function](https://github.com/asparius/mteb/blob/9733d06764f71cddf3755993b49f6f1006609903/mteb/load_results/load_results.py#L175C1-L175C87) does not read model_meta files however this [file](https://github.com/embeddings-benchmark/results/blob/main/results/bge-large-en-v1.5/d4aa6901d3a41ba39fb536a557fa166f842b0e09/model_metaInstruct.json) causes an error due to misnaming. Since it is the only file, perhaps we could rename it to model_meta.json as all other meta files. @KennethEnevoldsen @Muennighoff

**Comment by Samoed** [comment]
@KennethEnevoldsen I think that this was closed by #27
