### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/results#44]
To facilitate more PRs in this repo, we need pre-commit hooks setup such that most if not all of the github CI workflows can run locally.

**Comment by Samoed** [comment]
What checks do you want to add?

**Comment by isaac-chung** [comment]
As mentioned, all of the GH CI workflows in this repo. See also https://github.com/embeddings-benchmark/results/blob/main/CONTRIBUTING

**Comment by KennethEnevoldsen** [comment]
The 10MB conversation takes quite a while. Probably wouldn't run it as a commit hook, however, we could add a checklist to the PR or a contribution guideline

**Comment by isaac-chung** [comment]
Sure! Let's merge this with https://github.com/embeddings-benchmark/results/issues/45 then.
