### ISSUE TITLE
Scores are multiplied by 100 by default in old results

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/results#48]
Hey @Samoed! We accidentally used scores multiplied by 100 from the old leaderboard.
Can you fetch them and divide them by 100 as all other scores are in the benchmark?
Also can we add some safeguards against introducing duplicate results?

**Comment by x-tabdeveloping** [comment]
![newplot](https://github.com/user-attachments/assets/9798f45a-b95a-431c-af86-3d180d838fd9)

**Comment by Samoed** [comment]
What safeguards do you want?

**Comment by x-tabdeveloping** [comment]
Nothing, sorry, don't worry about duplicates yet, I'm looking into stuff
