### ISSUE TITLE
Couldn't get enough model_meta.json by using load_external.py

### ISSUE THREAD

**Issue by small-starriest** [embeddings-benchmark/results#52]
API = HfApi().
Using this api I only can get littlemodel_meta.json and couldn't get some model_meta.json, such as BAAI__bge-reranker-v2-gemma and so on. So how to get enough model_meta.json?

**Comment by Samoed** [comment]
What do you mean?

**Comment by small-starriest** [comment]
I have added several models such as BAAI/bge-reranker-v2-gemma in the results folder, and under these model folders, I need to add the corresponding model_meta.json. Now I am running some of the code in load_external.py, which can automatically retrieve the model_meta.json of the corresponding models, but I cannot retrieve the model_meta.json of these models.

**Comment by Samoed** [comment]
Can you submit your results to see model_meta? I think it is better to continue the discussion in the following pr

**Comment by KennethEnevoldsen** [comment]
This seem to have gotten stale will close it - feel free to re-open
