### ISSUE TITLE
Re-name models to clearly separate instruction vs non-instruction models

### ISSUE THREAD

**Issue by orionw** [embeddings-benchmark/results#8]
From [Issue 1066](https://github.com/embeddings-benchmark/mteb/issues/1066) we should rename all models to be whether they used instructions or not, following the format of #7.

**Comment by KennethEnevoldsen** [comment]
Hmm is that really where we ended up? It might be better to add a layer of nesting, see:


related to: https://github.com/embeddings-benchmark/mteb/issues/1211

**Comment by KennethEnevoldsen** [comment]
I will close this - and refer discussion to https://github.com/embeddings-benchmark/mteb/issues/1211
